---
cloudflare_vars:
  kubernetes:
    acme:
      server: staging
    api:
      token:
        key: token
        name: cloudflare-api-token
    helm:
      chart:
        name: external-dns
        version: v1.14.4
      repository:
        name: external-dns
        org: kubernetes-sigs
        url: https://kubernetes-sigs.github.io
    gateway:
      domain: noty.cc
    namespace: kube-system
    policy: sync
    resources:
      limits:
        cpu: 400m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 64Mi
    secret:
      key: token
      name: cloudflare-api-token
    tls:
      cluster_issuer:
        name: cloudflare-cluster-issuer
      key_prefix: cloudflare-tls
