---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  ANSIBLE_LINT_FILE: "{{.ANSIBLE_DIR}}/.ansible-lint"
  ANSIBLE_REQUIREMENTS_FILE: "{{.ANSIBLE_DIR}}/collections/requirements.yaml"
  ANSIBLE_PIP_REQUIREMENTS_FILE: "{{.ANSIBLE_DIR}}/requirements.txt"

env:
  ANSIBLE_COLLECTIONS_PATH: "{{.VIRTUAL_ENV}}/collections"
  ANSIBLE_ROLES_PATH: "{{.VIRTUAL_ENV}}/collections/ansible_roles"
  ANSIBLE_VARS_ENABLED: "host_group_vars"
  ANSIBLE_LOCALHOST_WARNING: "False"
  ANSIBLE_INVENTORY_UNPARSED_WARNING: "False"

tasks:

  deps:
    desc: Set up Ansible dependencies
    deps: [":workstation:venv"]
    cmds:
    - '{{.VIRTUAL_ENV}}/bin/python3 -m pip install --upgrade --requirement "{{.ANSIBLE_PIP_REQUIREMENTS_FILE}}"'
    - '{{.VIRTUAL_ENV}}/bin/ansible-galaxy install --role-file "{{.ANSIBLE_REQUIREMENTS_FILE}}" {{if eq .force "true"}}--force{{end}}'
    preconditions:
    - {msg: "Missing Ansible requirements file", sh: "test -f {{.ANSIBLE_REQUIREMENTS_FILE}}"}
    - {msg: "Missing Pip requirements file", sh: "test -f {{.ANSIBLE_PIP_REQUIREMENTS_FILE}}"}
    sources:
    - "{{.ANSIBLE_REQUIREMENTS_FILE}}"
    - "{{.ANSIBLE_PIP_REQUIREMENTS_FILE}}"
    generates:
    - "{{.VIRTUAL_ENV}}/bin/ansible"
    - "{{.VIRTUAL_ENV}}/bin/ansible-galaxy"
    vars:
      force: '{{.force | default "true"}}'

  run:
    desc: Run an Ansible playbook for configuring a cluster
    summary: |
      Args:
        cluster: Cluster to run command against (required)
        playbook: Playbook to run (required)
    prompt: Run Ansible playbook '{{.playbook}}' against the '{{.cluster}}' cluster ... continue?
    deps: ["deps"]
    cmd: |
      {{.VIRTUAL_ENV}}/bin/ansible-playbook \
        --inventory {{.ANSIBLE_DIR}}/{{.cluster}}/inventory/hosts.yaml \
        {{.ANSIBLE_DIR}}/{{.cluster}}/playbooks/{{.playbook}}.yaml {{.CLI_ARGS}}
    requires:
      vars: ["cluster", "playbook"]
    preconditions:
      - test -d {{.ROOT_DIR}}/.venv
      - test -f {{.ANSIBLE_DIR}}/{{.cluster}}/inventory/hosts.yaml
      - test -f {{.ANSIBLE_DIR}}/{{.cluster}}/playbooks/{{.playbook}}.yaml
