---
cluster_vars:
  device:
    id: '2:2'
    name: 'ASMedia Technology'
    transport: usb
  hardware:
    architecture: aarch64
    product: 'Raspberry Pi'
  service:
    bluetooth:
      enabled: false
    cloud_init:
      enabled: false
    snapd:
      enabled: false
    unattended_upgrades:
      enabled: true
      mail_report: on-change
      remove_deps: 'true'
    wifi:
      enabled: false
  # ssh:
  #   authorized_key: "{{ lookup('ansible.builtin.env', 'HOME') + '/.ssh/id_ed25519.pub' }}"
