---
argocd_vars:
  kubernetes:
    application_set:
      replicas: 2
      resources:
        limits:
          cpu: 400m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 64Mi
    configs:
      cm:
        exec:
          enabled: true
      params:
        server:
          insecure: true
    controller:
      resources:
        limits:
          cpu: 400m
          memory: 256Mi
        requests:
          cpu: 200m
          memory: 128Mi
    dex:
      resources:
        limits:
          cpu: 400m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 64Mi
    helm:
      chart:
        name: argo-cd
        org: argoproj
        version: 6.8.1
      repository:
        name: argo-helm
        org: argoproj
        url: https://argoproj.github.io
    namespace: kube-system
    notifications:
      resources:
        limits:
          cpu: 400m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 64Mi
    redis:
      high_availability:
        enabled: true
      resources:
        limits:
          cpu: 400m
          memory: 256Mi
        requests:
          cpu: 200m
          memory: 128Mi
    repo_server:
      autoscaling:
        enabled: true
        min_replicas: 2.
        target:
          cpu_percentage: 60
          memory_percentage: 80
      resources:
        limits:
          cpu: 400m
          memory: 256Mi
        requests:
          cpu: 200m
          memory: 128Mi
    server:
      application:
        namespaces:
          - kube-system
      autoscaling:
        enabled: true
        min_replicas: 2
        target:
          cpu_percentage: 60
          memory_percentage: 80
      gateway:
        service: argo-cd-argocd-server
        subdomain: argocd
      infrastructure:
        annotations:
          io.cilium/lb-ipam-ips: 192.168.4.18
      resources:
        limits:
          cpu: 400m
          memory: 256Mi
        requests:
          cpu: 200m
          memory: 128Mi
      user:
        name: chalk
  release:
    checksums: cli_checksums.txt
    file: argocd-linux-arm64
    repository:
      name: argo-cd
      org: argoproj
    version: v2.11.0
