---
prometheus_vars:
  kubernetes:
    alertmanager:
      gateway:
        service: monitoring-kube-prometheus-alertmanager
        subdomain: alertmanager
      infrastructure:
        annotations:
          io.cilium/lb-ipam-ips: 192.168.4.21
      replicas: 2
      resources:
        limits:
          cpu: 400m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 64Mi
      storage: 5Gi
    helm:
      chart:
        name: kube-prometheus-stack
        prefix: monitoring
        version: v58.5.0
      repository:
        name: helm-charts
        org: prometheus-community
        url: https://prometheus-community.github.io
    grafana:
      gateway:
        service: monitoring-grafana
        subdomain: grafana
      infrastructure:
        annotations:
          io.cilium/lb-ipam-ips: 192.168.4.22
      secret:
        name: grafana-credentials
      user:
        name: admin
    namespace: kube-system
    prometheus:
      gateway:
        service: monitoring-kube-prometheus-prometheus
        subdomain: prometheus
      infrastructure:
        annotations:
          io.cilium/lb-ipam-ips: 192.168.4.23
      resources:
        limits:
          cpu: 1
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 64Mi
      storage: 50Gi
